language: ruby

before_script:
  - gem install jekyll

script:
  - git clone https://github.com/gap-system/Mixer.git
  - cd Mixer
  - make
  - rm -rf testsite
  - cd ..
  - ./Mixer/mixer.py -f
  - etc/sync_mixer_to_jekyll.py
  - jekyll build
